### ISSUE TITLE
[BUG] Build Issue in Xcode 14.1 Beta

### ISSUE THREAD

**Issue by lewis-smith** [superwall-me/paywall-ios#67]
## New issue checklist
- [x] I have reviewed the [`README`](https://github.com/superwall-me/paywall-ios/blob/master/README.md) and [documentation](https://docs.superwall.com/docs)
- [x] I have searched [existing issues](https://github.com/superwall-me/paywall-ios/issues) and this is not a duplicate
- [x] I have attempted to reproduce the issue and include an example project.

### General information

- `Paywall` version: 2.4.1
- iOS version(s): 16.1
- CocoaPods/Carthage version (if applicable):
- Xcode version: 14.1.0 Beta
- Devices/Simulators affected: All?
- Reproducible in the demo project? (Yes/No): I made a totally fresh project
- Related issues: n/a

### Describe the bug
An empty project won't build in Xcode 14.1 once Superwall is added as a dependency.
I noticed this in my real project so I created an empty project with no new code and build fails as soon as Superwall is a dependency

`/Applications/Xcode-14.1.0-Beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.1.sdk/System/Library/Frameworks/GameController.framework/Headers/GCPhysicalInputElement.h:44:73: 'GCPhysicalInputElement' is unavailable: not available on iOS`

This is probably an Apple bug, but if it's not resolved we will have to remove Superwall.

### Steps to reproduce
- Open Xcode 14.1.0 Beta
- Create a new iOS app project (I used the storyboard template)
- Add `https://github.com/superwall-me/paywall-ios` as an SPM dependency
- Build the project

### Other Information
I've attached the full build log in case it's helpful. Here's a screenshot as that's probably easier to look at:
<img width="1499" alt="CleanShot 2022-09-18 at 11 03 23@2x" src="https://user-images.githubusercontent.com/1905433/190913859-e28a125f-a344-4760-b0bd-afd038a3987a.png">

I've googled for this error and can't find anything.

[Build Superwall 14.1_2022-09-18T10-49-27.txt](https://github.com/superwall-me/paywall-ios/files/9594234/Build.Superwall.14.1_2022-09-18T10-49-27.txt)

**Comment by lewis-smith** [comment]
As a temporary workout around to allow development on Live Activities to continue whilst this gets resolved I'm using Xcode 14.0 b5 as this is the last build that supports Live Activities AND builds Superwall.

**Comment by yusuftor** [comment]
Hey @lewis-smith, thanks for the detailed bug report.

This is a bug with Apple's own `GameController` module. We support GameController within Superwall which is why it's failing when you try to import Superwall. Importing GameController into a blank project gives me the same error. I've filed a bug report with apple (FB11538209), but it would be good if you could also file a bug report. I've also mentioned it in the Apple developer forums: https://developer.apple.com/forums/thread/714980

We''ll keep an eye on that and if it's still not fixed by the time Xcode 14.1 comes out we may have to rethink GameController support.

**Comment by lewis-smith** [comment]
Thanks @yusuftor, I'll file a feedback with Apple.

Just to update anyone else, Live Activities have changed quite a bit since 14.0 b5 so it's not possible to code for 14.1 using that Xcode :(

**Comment by lewis-smith** [comment]
Filed a dupe and sent a message to our Dev Relations rep. Fingers crossed it gets fixed soon. Thanks for such a quick and diligent response.

**Comment by yusuftor** [comment]
Great, thank you! Please update me on here if you hear anything and I'll do the same.

**Comment by lewis-smith** [comment]
This is resolved in beta 3. Other people in the forum thread that @yusuftor created confirm too.
