### ISSUE TITLE
Unable to manually trigger paywall on first launch if triggered paywall on session_start

### ISSUE THREAD

**Issue by seth35us** [superwall-me/paywall-ios#72]
On initial install if I trigger the paywall on session_start, then [manually trigger the paywall in SwiftUI](https://docs.superwall.com/docs/triggering-paywalls), the manual trigger does not display a paywall or fail. 

If I kill the application and then relaunch the manual trigger of the paywall will work after the paywall is triggered through the session_start event. 

The error is only occurring on the very first launch of the application. 

Secondarily, I can create an issue for this if needed, but the paywall sometimes takes more than 4 seconds to launch on session_start. Is there a recommended way to handle this so the user does not need to wait for a paywall to show up? I don't notice the issue in the FitnessAI app.

**Comment by yusuftor** [comment]
Hey @seth35us, re your first point, I tried to replicate your issue but couldn't. I added the `session_start` trigger to a campaign, did a fresh install of our SwiftUI example app and then proceeded to see the `session_start` paywall, followed by the manually triggered paywall. I'm wondering whether a state issue is occurring in your app causing it to fail?
Can you reproduce this issue in our sample SwiftUI app?

Re your second point, we have to delay all triggers until we've received a callback from the server to get the paywall configuration. It's likely dependent on your internet connection. Or if you're running in sandbox from testflight/dev then it could be the delay in getting products from App Store Connect, which wouldn't occur in the live version.

**Comment by seth35us** [comment]
Hey @yusuftor, you can close this issue. After digging for a while, I noticed that I was manually triggering the paywall on init at the same time the event triggered the paywall. The error only occurred on first launch because it was triggered through remote config. 

For some reason after triggering the paywall on init at the same time as the event triggered the paywall broke the paywall display after that. 

I have removed the code that manually triggered the paywall on init, since the events are triggering it. 

For the second point I have been noticing the issue on Test Flight, so perhaps it is only a lower environment issue. 

I appreciate your help.

**Comment by yusuftor** [comment]
Thanks for the follow up and glad it’s been sorted!
