### ISSUE TITLE
[BUG] - Disruptive "Waiting to Purchase" Alert

### ISSUE THREAD

**Issue by michaeljajou** [superwall-me/paywall-ios#76]
## New issue checklist
- [x] I have reviewed the [`README`](https://github.com/superwall-me/paywall-ios/blob/master/README.md) and [documentation](https://docs.superwall.com/docs)
- [x] I have searched [existing issues](https://github.com/superwall-me/paywall-ios/issues) and this is not a duplicate

### General information

- `Paywall` version: 2.5.2
- iOS version(s): 16.0.2
- Xcode version: 14.0.1
- Devices/Simulators affected: iPhone 12 Pro Max

### Describe the bug
Upon making a purchase, the "Waiting to Purchase" modal appears just after a few seconds, claiming that the connection may be offline when in fact the purchase will still happen successfully. Network connection is strong at 186 Mbps. In fact it happens just as soon as the payment sheet is presented (the user hasn't confirmed with Apple that they would like to subscribe yet). 

### Steps to reproduce
1. Trigger a paywall
2. Purchase a product/or restore purchases
3. Wait a few seconds and an alert controller as shown in the image below will appear. 

![Alert while payment sheet is presented](https://user-images.githubusercontent.com/45440199/195444684-195ffca2-a858-4bc7-bf12-5b481390ce85.jpg)

![Alert while payment is successfully being processed](https://user-images.githubusercontent.com/45440199/195444752-42da9f72-8a1c-4c89-892a-6e8f55e569fa.jpg)

**Comment by yusuftor** [comment]
Hi @michaeljajou, thanks for the bug report. This is a known issue with users who are using StoreKit 2. Can you confirm whether this is the case? We don’t officially support StoreKit 2 yet but are working on improving this in the 3.0 release. If you’re using revenuecat you can specifically set it to use StoreKit 1.

**Comment by michaeljajou** [comment]
Ah thank you for the quick response! Sounds good, I believe I am using StoreKit 2. Are there any downsides to switching down to StoreKit 1?

**Comment by michaeljajou** [comment]
I am using RevenueCat, where can I find how to make that switch?

**Comment by yusuftor** [comment]
If you're handling storekit yourself then it's just a lot easier but with StoreKit 2, but I don't believe there are any disadvantages when using RevenueCat. You can do it like this when configuring `Purchases`:

```
Purchases.configure(
  with: .init(withAPIKey: configuration.environment.revenueCatApiKey)
    .with(usesStoreKit2IfAvailable: false)
)
```

**Comment by michaeljajou** [comment]
Thank you, works great!

**Comment by yusuftor** [comment]
Great! Closing this issue now. Thanks!
