### ISSUE TITLE
[FEATURE REQUEST] - Sandbox Testing Environment

### ISSUE THREAD

**Issue by michaeljajou** [superwall-me/paywall-ios#77]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
An environment for testing vs production. As I am testing out the flow of my paywalls, and making sure everything is working properly - the conversion numbers on my dashboard are now filled with sandbox data :( 

Are there any recommendations for setting up a test environment?

**Describe alternatives you've considered**
Creating a separate app in Superwall

**Comment by yusuftor** [comment]
Hey, we’ve had this feature requested quite a bit and are aware that this is an issue. Until we’ve got something ready to share with you to solve this I’d recommend creating a separate Superwall app for testing. Sorry for the inconvenience!
