### ISSUE TITLE
[BUG] - Video Template has weird intro animation before playing

### ISSUE THREAD

**Issue by michaeljajou** [superwall-me/paywall-ios#81]
## New issue checklist
- [x] I have reviewed the [`README`](https://github.com/superwall-me/paywall-ios/blob/master/README.md) and [documentation](https://docs.superwall.com/docs)
- [x] I have searched [existing issues](https://github.com/superwall-me/paywall-ios/issues) and this is not a duplicate
- [ ] I have attempted to reproduce the issue and include an example project.

### General information

- `Paywall` version: 2.5.2
- iOS version(s): 16.0.3
- Xcode version: 14.0
- Devices/Simulators affected: iPhone 12 Pro Max
- Reproducible in the demo project? (Yes/No): N/A
- Related issues:

### Describe the bug
Using the A3 Superwall Video Template - before the video starts playing it animates in from the corner and then flashes player controls. 

Also with my specific video - the video just never plays (I'm certain this is due to the format of my video.) Are there any optimal formats/video requirements documented in order to make video playback smoother? 
![Preview](https://user-images.githubusercontent.com/45440199/196803896-4e68f932-c635-451c-956b-d3ea99dc3a35.jpg)

**Comment by anglinb** [comment]
👋 Hey @michaeljajou I think the jitter _should_ only affect the editor and now the preview in app as the SDK.  However, I don't see the video loading on iOS either. I'm trying to reproduce the issue and noticing that safari is not loading the video at all, even on desktop so I'm going to continue to investigate why that might be happening.

**Comment by anglinb** [comment]
Ok so there was something weird going on with the mp4 you had. I downloaded it, ran it through `ffmpeg` and uploaded it again and it works 🤷 

Here's the updated one: https://static.superwallassets.com/ePWZAoG6VTx9l3GkYCZBm

Here's the `ffmpeg` command I used: `ffmpeg -i wa29TTOD08bWnwDpXr1k7.mp4 -pix_fmt yuv420p -crf 18 good.mp4`

As far as the jitter, I am still seeing that on iOS. It's likely an issue with the templating in the web view which I'll continue to look into.

**Comment by michaeljajou** [comment]
You're the best, appreciate it! @anglinb 

So the web view is using the Safari AVPlayerViewController under the hood? So we'll use that to test video compatibility, we had been exporting using Youtube Settings out of premiere but will switch back to H264

Also on the flicker - I noticed a much smoother appearance if I set a specific width/height for the video box. For the width i'm setting it to be 100% and for the height I used 143vw

**Comment by michaeljajou** [comment]
Ah actually - that doesn't seem like the best approach since it doesn't scale properly across all the devices (I tried presetting the height using 70vh as well, but no luck.)

Either way, paywall looks so good we're going to push it to our prod app. But in the future if there is a solution for:
- removing the flash of video controls
- Fixing the sizing adjustment on appearance

That will make it much more epic than it already is!

**Comment by anglinb** [comment]
> You're the best, appreciate it! @anglinb

🙌 Happy to help!!

> So the web view is using the Safari AVPlayerViewController under the hood? So we'll use that to test video compatibility, we had been exporting using Youtube Settings out of premiere but will switch back to H264

We're just using a modified `WKWebView` so maybe that's being used under the hood. Hmm yeah H264 sounds like a safe bet. I noticed that Safari on Mac and Finder didn't like the output either FWIW. If you go directly to the old url or download the file and hover in Finder it won't play. 


> Either way, paywall looks so good we're going to push it to our prod app. But in the future if there is a solution for:
> - removing the flash of video controls
> - Fixing the sizing adjustment on appearance

Definitely, excited for you all to launch! I made a ticket to track this internally to see if we can fix up our templating to account for replacing videos like this.

**Comment by michaeljajou** [comment]
> Definitely, excited for you all to launch! I made a ticket to track this internally to see if we can fix up our templating to account for replacing videos like this.

Thank you! To clarify, the flashing of controls and initial resizing was happening with even the original videos as part of the template
